mirror_base_url = "https://opkg.calculinux.org"
machine = "walnascar"
download_dir = "/var/cache/calculinux-update"

[[channels]]
name = "Walnascar Release"
path = "/update/walnascar/release"
enable = true

[[channels]]
name = "Walnascar Continuous"
path = "/update/walnascar/continuous"
enable = false

[[channels]]
name = "Walnascar PR Builds"
path = "/update/walnascar/pr"
enable = false
